/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProdcutService } from "../prodcut.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProdcutCreateInput } from "./ProdcutCreateInput";
import { Prodcut } from "./Prodcut";
import { ProdcutFindManyArgs } from "./ProdcutFindManyArgs";
import { ProdcutWhereUniqueInput } from "./ProdcutWhereUniqueInput";
import { ProdcutUpdateInput } from "./ProdcutUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProdcutControllerBase {
  constructor(
    protected readonly service: ProdcutService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Prodcut })
  @nestAccessControl.UseRoles({
    resource: "Prodcut",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProdcut(
    @common.Body() data: ProdcutCreateInput
  ): Promise<Prodcut> {
    return await this.service.createProdcut({
      data: {
        ...data,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,

        order: data.order
          ? {
              connect: data.order,
            }
          : undefined,

        review: data.review
          ? {
              connect: data.review,
            }
          : undefined,
      },
      select: {
        category: {
          select: {
            id: true,
          },
        },

        colors: true,
        createdAt: true,
        description: true,
        discountedPrice: true,
        id: true,
        images: true,

        order: {
          select: {
            id: true,
          },
        },

        review: {
          select: {
            id: true,
          },
        },

        title: true,
        titlePrice: true,
        updatedAt: true,
        varients: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Prodcut] })
  @ApiNestedQuery(ProdcutFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Prodcut",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prodcuts(@common.Req() request: Request): Promise<Prodcut[]> {
    const args = plainToClass(ProdcutFindManyArgs, request.query);
    return this.service.prodcuts({
      ...args,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        colors: true,
        createdAt: true,
        description: true,
        discountedPrice: true,
        id: true,
        images: true,

        order: {
          select: {
            id: true,
          },
        },

        review: {
          select: {
            id: true,
          },
        },

        title: true,
        titlePrice: true,
        updatedAt: true,
        varients: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Prodcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prodcut",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async prodcut(
    @common.Param() params: ProdcutWhereUniqueInput
  ): Promise<Prodcut | null> {
    const result = await this.service.prodcut({
      where: params,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        colors: true,
        createdAt: true,
        description: true,
        discountedPrice: true,
        id: true,
        images: true,

        order: {
          select: {
            id: true,
          },
        },

        review: {
          select: {
            id: true,
          },
        },

        title: true,
        titlePrice: true,
        updatedAt: true,
        varients: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Prodcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prodcut",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProdcut(
    @common.Param() params: ProdcutWhereUniqueInput,
    @common.Body() data: ProdcutUpdateInput
  ): Promise<Prodcut | null> {
    try {
      return await this.service.updateProdcut({
        where: params,
        data: {
          ...data,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,

          order: data.order
            ? {
                connect: data.order,
              }
            : undefined,

          review: data.review
            ? {
                connect: data.review,
              }
            : undefined,
        },
        select: {
          category: {
            select: {
              id: true,
            },
          },

          colors: true,
          createdAt: true,
          description: true,
          discountedPrice: true,
          id: true,
          images: true,

          order: {
            select: {
              id: true,
            },
          },

          review: {
            select: {
              id: true,
            },
          },

          title: true,
          titlePrice: true,
          updatedAt: true,
          varients: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Prodcut })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Prodcut",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProdcut(
    @common.Param() params: ProdcutWhereUniqueInput
  ): Promise<Prodcut | null> {
    try {
      return await this.service.deleteProdcut({
        where: params,
        select: {
          category: {
            select: {
              id: true,
            },
          },

          colors: true,
          createdAt: true,
          description: true,
          discountedPrice: true,
          id: true,
          images: true,

          order: {
            select: {
              id: true,
            },
          },

          review: {
            select: {
              id: true,
            },
          },

          title: true,
          titlePrice: true,
          updatedAt: true,
          varients: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
